#!/bin/sh
# rebuild
rm -rf _site
webpack
jekyll build

echo 'Compressing...'
tar -czvf archive.tar.gz ./_site --exclude=./_site/deploy* >/dev/null 2>&1
echo 'Compressed to archive.tar.gz'

echo 'Start transfer compressed file to ali cloud...'
scp -r ./archive.tar.gz root@47.74.183.6:~

echo 'Unpack tar file in the remote server...'
ssh alia "tar -xzvf archive.tar.gz -C /srv/www --transform 's/_site/cheeger.com/' >/dev/null 2>&1;rm archive.tar.gz;exit"
rm archive.tar.gz
echo 'Deployed && archive.tar.gz removed'
